name: sangu_websocket
version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.0
  web_socket_channel: ^1.1.0
  json_annotation: ^3.0.1
  http: ^0.12.1
  uuid: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.9.0
